### ISSUE TITLE
SpringBoard high CPU usage

### ISSUE THREAD

**Issue by gilshahar7** [CreatureSurvive/motuumLS-IssueTracker#14]
When i have the tweak installed I'm having a higher than normal springboard CPU usage (around 25%, even when I'm on the homescreen or inside an app.)

The high usage only starts after some time from a respring.

**Comment by axxng** [comment]
Seems like this is not random. I tested it by swiping back and forth between today view and default view, and CPU usage goes up consistently, and never goes down until a respring.

**Comment by CreatureSurvive** [comment]
This has been patched for a while now, I should really do a better job closing issues.
