### ISSUE TITLE
Springboard Crash?

### ISSUE THREAD

**Issue by Striter100** [CreatureSurvive/motuumLS-IssueTracker#15]
Crash reporter claimed motuum was the main suspect, got concerned because in the Syslog it says something about a "malloc error" and I've never seen that before with any crash.

Crash log: https://pastebin.com/pcHnSaf4

Syslog: https://pastebin.com/m0ciAipS

**Comment by CreatureSurvive** [comment]
Closing this issue, it's​ been fixed for a few releases now.
