### ISSUE TITLE
Springboard crash

### ISSUE THREAD

**Issue by Striter100** [CreatureSurvive/motuumLS-IssueTracker#17]
Crash reporter said lockhtml4 was the main suspect but the Syslog said motuumls? Not sure, but figured I'd share it with you anyways in case it's something related to motuum

Syslog: https://pastebin.com/kr8j3FBC

Crash log: https://pastebin.com/gEkWEcVV

**Comment by CreatureSurvive** [comment]
Closing this as it appears to have been fixed in a previous update.
