### ISSUE TITLE
Battery State with Notifications doesnt work very well with Modern

### ISSUE THREAD

**Issue by mrchhaya** [CreatureSurvive/motuumLS-IssueTracker#18]
https://gfycat.com/GrandioseSickAmericanblackvulture

**Comment by CreatureSurvive** [comment]
could you explain what you mean?

**Comment by mrchhaya** [comment]
Yeah sorry the link didnt go through for some reason

**Comment by CreatureSurvive** [comment]
it looks to be updating properly, just need to adjust the position of either the battery or the noitifications

**Comment by CreatureSurvive** [comment]
Closing this as a configuration issue
