### ISSUE TITLE
No Weather

### ISSUE THREAD

**Issue by liquid-me** [CreatureSurvive/motuumLS-IssueTracker#2]
Can't get weather working. (Thanks, Willem)

**Comment by liquid-me** [comment]
After trying out several options of weather alignment and variations of settings (like order of '-t-i'*'-c'*'-l') weather suddenly appeared on LS.

So short story: it works now!

**Comment by CreatureSurvive** [comment]
This seems to be an issue with the laying out labels containing the weather icon. This is already fixed and will be included in the next build.
