### ISSUE TITLE
Screen wake for notifications is cause issues

### ISSUE THREAD

**Issue by shampost** [CreatureSurvive/motuumLS-IssueTracker#8]
Although the toggle in the notifications tab for this is off, it seems to still suppress the screen wake. I've noticed that it happens normally/while playing music.

I'm fairly sure there are no other tweaks which I have installed that have the capability to do this.

**Comment by CreatureSurvive** [comment]
The bug in motuumLS preferences that caused this issue should be fixed as of version2.8.9.
